### ISSUE TITLE
Appstore submission issue: ITMS-91056: Invalid privacy manifest 

### ISSUE THREAD

**Issue by jenjo27** [newrelic/newrelic-cordova-plugin#88]
Getting following error while submitting an iOS application:

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

Can anyone please help on the same?.

<img width="612" alt="image" src="https://github.com/newrelic/newrelic-cordova-plugin/assets/7285615/f655bb36-9fff-4576-836a-3f6cd3e6d246">

**Comment by ndesai-newrelic** [comment]
@jenjo27 which version of cordova agent are you using?

**Comment by jenjo27** [comment]
Hi @ndesai-newrelic. Thanks for the immediate response. 
I am using ionic framework. Hope the following info helps.

![image](https://github.com/newrelic/newrelic-cordova-plugin/assets/7285615/da0de6a4-43ce-4c60-898e-2494cf112011)


- Thnx.

**Comment by ndesai-newrelic** [comment]
@jenjo27If you are using the latest version of the New Relic Cordova plugin, the issue you are facing should be resolved. The latest plugin release includes fixes and improvements that address the problem you are experiencing.

**Comment by jenjo27** [comment]
@ndesai-newrelic After updating the latest newrelic version, still seeing the same privacy config properties.
![image](https://github.com/newrelic/newrelic-cordova-plugin/assets/7285615/9c10ecac-9f0b-4bba-a430-ac8f4a4b29e4)

**Comment by jenjo27** [comment]
@ndesai-newrelic Again getting the same error message.
<div align="center" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Please correct the following issues and upload a new binary to App Store Connect.ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.Apple Developer Relations | Please correct the following issues and upload a new binary to App Store Connect.ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.Apple Developer Relations
-- | --
Please correct the following issues and upload a new binary to App Store Connect.ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.Apple Developer Relations

</div><p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 11pt; font-family: Aptos, sans-serif;"><br><br>Regards,<br>Sasi W.</span></p>

**Comment by jenjo27** [comment]
@ndesai-newrelic 
Resolved ITMS-91056: Invalid privacy manifest issue.
- Thanks
